import type { MetadataRoute } from 'next'

/**
 * Web app manifest, served at /manifest.webmanifest and linked by Next.
 *
 * start_url carries `source=pwa` so launches from the home-screen icon can
 * be told apart from browser visits; the root page forwards the parameter
 * to /home or /splash and the analytics wrapper reads it there.
 * Icons are generated by `npm run pwa:assets` (scripts/pwa).
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: 'Get Lucky Hole in One Challenge',
    short_name: 'Get Lucky',
    description: 'Back yourself on any par-3. Record your hole-in-one and claim up to R1,000,000.',
    id: '/',
    start_url: '/?source=pwa',
    scope: '/',
    display: 'standalone',
    orientation: 'portrait',
    theme_color: '#345231',
    background_color: '#345231',
    lang: 'en-ZA',
    categories: ['sports', 'games'],
    icons: [
      { src: '/icons/icon-192.png', sizes: '192x192', type: 'image/png', purpose: 'any' },
      { src: '/icons/icon-256.png', sizes: '256x256', type: 'image/png', purpose: 'any' },
      { src: '/icons/icon-384.png', sizes: '384x384', type: 'image/png', purpose: 'any' },
      { src: '/icons/icon-512.png', sizes: '512x512', type: 'image/png', purpose: 'any' },
      { src: '/icons/icon-maskable-512.png', sizes: '512x512', type: 'image/png', purpose: 'maskable' },
    ],
  }
}
